enabled: true
prefix: "&7&o&l2B&6 "
suffix: "\n&7&o&lAU&6 "
motds:
  - "Sponsored by Raid Shadow Legends Hypocalyper360 and quacklypvp"
  - "QLD ON TOP"
  - "NSW is the superior state"
  - "Ownership has been passed over to veteran player nattf"
  - "ᄅqᄅʇ ∀nsʇɹɐlᴉɐ"
  - "Abos are just Australian Bears"
  - "If you play 2b2t you have a brain disiblity"
  - "&oinsert epic funny motd haha"
  - "Pinging.."
  - "Clockwork On Top"
  - "This MOTD was made by a certified Australian!"
  - "Australia: 99% Asians, 1% Australians"
  - "Hosted by Telstra"
  - "Sub to Fax"
  - "Boats disabled due to exploit"
  - "Sex. -waifsu"
  - "Comically overused joke!"
  - "Buy Faxhax, with working q skip! – dotDucky"
  - "Get sigma today and join the world of crypto mining! – dotDucky"
  - "PancakeMix On Top -dotDucky"
  - "Vegemite tastes good on toast"
  - ">why is the invisible man punching me"
  - ">Server will now redirect to hypixel"
  - "time to smoke pizza and eat weed"
  - "now with more cunts begging for kits"
  - ">dm bstar#1600 for duping method/s"
  - "my uncle touched my no no place on september 11th 2001"
  - "ur mum plays here"
  - "more than just a block game"
  - "just a block game"
  - "Welcome, FaxMachine5781"
  - "Welcome, Fit"
  - "Welcome, Virl"
  - "Welcome, Rooster548"
  - "Welcome, bstar"
  - "Welcome, T0rnadoguy"
  - "Yeah I have made a mistake"
  - "Something new disabled weekly!"
  - "melon"
  - "15683, 127, -320000"
  - "what are you waiting for?"
  - "2b2t: Kangaroo Edition"
  - "Remember to be friendly!"
  - "gratitude goes a long way"
  - "FFFFFUUUUUCCCCKKKKIIINNGGGGG RRRRRRAAAAAAGGGGGGEEEEEEE"
  - "soundcloud rappers only"
  - "overindividualistically"
  - "have a go, ya mug"
  - "But Australian intelligence doesn't trust anyone who speaks Russian or German."
  - "built like a brick shithouse."
  - "dont piss in my pocket"
  - "six of one, half a dozen of another"
  - "dont piss in my pocket"
  - "\"I’m chockers mate.\""
  - "dry as a dingo’s donger"
  - "not the sharpest tool in the shed"
  - "don't be a flaming galah"
  - "That's not a knife… THAT's a knife."
  - "muzzaa is sexy"
  - "sub to wao"
  - "i got a sub 10 run on this server"
  - "If pigs are so smart why then why do 2/3 build their houses so poorly."
  - "Mr_Fusion1000 is the Emperor of 2b2t AU"
  - "CookedDogMeat best pvper"
  - "cones cones cones"
  - "Lnadav keeps winning!"
  - "Lnadav is a femboy"
  - "approved by FitMC"
  - "Tater kit shop has the best quality items and stashes!"
  - "Message Lnadav on discord for thigh pics"
  - "femboys welcome!"
  - "centrelink approved"
  - "dans x Lnadav sex tape when???"
  - "IM ON SMOKO, SO LEAVE ME ALONE!"
  - "tater kit shopped is sponsored by remainingtoest! "
  - "Whoop! Too fast!"
  - "How a real 2b2t criminal donated to 2b2t Australia :o"
  - "this account has been token logged by travis. 顶部的per download wurst-plus-three是安全的 emp搞砸"
  - "Fusion On Top"
  - "\"Fuck\" -Eonexe"
  - "2b2t australia 2.0 when"